package hello;
import hello.models.Listing;
import hello.repositories.ListingRepository;


import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ListingRepository listingRepository;

    private static List<Listing> listings = new ArrayList<Listing>();

    @GetMapping(value = { "/", "/index" })
    public String index(Model model) {
        listings.clear();

        listingRepository.findAll().forEach(listings::add);

        String message = "this is a message";
        model.addAttribute("message", message);
        model.addAttribute("listings", listings);

        return "index";
    }

    @GetMapping("/greeting")
    public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
        model.addAttribute("name", name);
        return "greeting";
    }

}