server:
  error:
    include-stacktrace: always
  servlet:
    session:
      cookie:
        name: payment_microservice_cookie_name
spring:
  jmx:
    default-domain: platform-payment
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: dev
payment:
  platform_cut: 0.4
