spring:
  datasource:
    url: jdbc:mysql://localhost/payment?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: O53C5oybLAOMB4y
  main:
    banner-mode: 'off'
auth:
  auth_servlet_url: http://localhost:8081
  client_id: app_developer
  client_secret: MbBVWtfMOJHXk4FS0uotKiF6c5mBy8LzXGKLm0vMl3U=
  redirect_uri: http://localhost:8080/auth/callback
